package cr.ac.una.prograIV.AirLine.domain;
// Generated 18-may-2017 21:04:02 by Hibernate Tools 4.3.1



/**
 * Asiento generated by hbm2java
 */
public class Asiento  implements java.io.Serializable {


     private String pkNumero;
     private Avion avion;
     private Tiquete tiquete;

    public Asiento() {
    }

    public Asiento(String pkNumero, Avion avion, Tiquete tiquete) {
       this.pkNumero = pkNumero;
       this.avion = avion;
       this.tiquete = tiquete;
    }
   
    public String getPkNumero() {
        return this.pkNumero;
    }
    
    public void setPkNumero(String pkNumero) {
        this.pkNumero = pkNumero;
    }
    public Avion getAvion() {
        return this.avion;
    }
    
    public void setAvion(Avion avion) {
        this.avion = avion;
    }
    public Tiquete getTiquete() {
        return this.tiquete;
    }
    
    public void setTiquete(Tiquete tiquete) {
        this.tiquete = tiquete;
    }




}


