package cr.ac.una.prograIV.AirLine.domain;
// Generated 12-may-2017 14:55:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Avion generated by hbm2java
 */
public class Avion  implements java.io.Serializable {


     private int pkId;
     private int ano;
     private int modelo;
     private String marca;
     private int cantPasajeros;
     private Set<Asiento> asientos = new HashSet<Asiento>(0);

    public Avion() {
    }

	
    public Avion(int pkId, int ano, int modelo, String marca, int cantPasajeros) {
        this.pkId = pkId;
        this.ano = ano;
        this.modelo = modelo;
        this.marca = marca;
        this.cantPasajeros = cantPasajeros;
    }
    public Avion(int pkId, int ano, int modelo, String marca, int cantPasajeros, Set<Asiento> asientos) {
       this.pkId = pkId;
       this.ano = ano;
       this.modelo = modelo;
       this.marca = marca;
       this.cantPasajeros = cantPasajeros;
       this.asientos = asientos;
    }
   
    public int getPkId() {
        return this.pkId;
    }
    
    public void setPkId(int pkId) {
        this.pkId = pkId;
    }
    public int getAno() {
        return this.ano;
    }
    
    public void setAno(int ano) {
        this.ano = ano;
    }
    public int getModelo() {
        return this.modelo;
    }
    
    public void setModelo(int modelo) {
        this.modelo = modelo;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getCantPasajeros() {
        return this.cantPasajeros;
    }
    
    public void setCantPasajeros(int cantPasajeros) {
        this.cantPasajeros = cantPasajeros;
    }
    public Set<Asiento> getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Set<Asiento> asientos) {
        this.asientos = asientos;
    }




}


