package cr.ac.una.prograIV.AirLine.domain;
// Generated 18-may-2017 21:04:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int pkId;
     private Usuario usuario;
     private String nombre;
     private String apellidos;
     private String email;
     private Date fechaNacimiento;
     private int celular;
     private String direccion;
     private Float direccion2;
     private Compra compra;
     private Set<Tiquete> tiquetes = new HashSet<Tiquete>(0);

    public Cliente() {
    }

	
    public Cliente(int pkId, Usuario usuario, String nombre, String apellidos, String email, Date fechaNacimiento, int celular, String direccion) {
        this.pkId = pkId;
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.email = email;
        this.fechaNacimiento = fechaNacimiento;
        this.celular = celular;
        this.direccion = direccion;
    }
    public Cliente(int pkId, Usuario usuario, String nombre, String apellidos, String email, Date fechaNacimiento, int celular, String direccion, Float direccion2, Compra compra, Set<Tiquete> tiquetes) {
       this.pkId = pkId;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
       this.fechaNacimiento = fechaNacimiento;
       this.celular = celular;
       this.direccion = direccion;
       this.direccion2 = direccion2;
       this.compra = compra;
       this.tiquetes = tiquetes;
    }
   
    public int getPkId() {
        return this.pkId;
    }
    
    public void setPkId(int pkId) {
        this.pkId = pkId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getCelular() {
        return this.celular;
    }
    
    public void setCelular(int celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Float getDireccion2() {
        return this.direccion2;
    }
    
    public void setDireccion2(Float direccion2) {
        this.direccion2 = direccion2;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Set<Tiquete> getTiquetes() {
        return this.tiquetes;
    }
    
    public void setTiquetes(Set<Tiquete> tiquetes) {
        this.tiquetes = tiquetes;
    }




}


