package cr.ac.una.prograIV.AirLine.domain;
// Generated 18-may-2017 21:04:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int clienteId;
     private Cliente cliente;
     private Tiquete tiquete;
     private Date fecha;
     private String direccionEnvio;
     private int total;
     private String tarjeta;
     private Date vencimiento;

    public Compra() {
    }

    public Compra(Cliente cliente, Tiquete tiquete, Date fecha, String direccionEnvio, int total, String tarjeta, Date vencimiento) {
       this.cliente = cliente;
       this.tiquete = tiquete;
       this.fecha = fecha;
       this.direccionEnvio = direccionEnvio;
       this.total = total;
       this.tarjeta = tarjeta;
       this.vencimiento = vencimiento;
    }
   
    public int getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Tiquete getTiquete() {
        return this.tiquete;
    }
    
    public void setTiquete(Tiquete tiquete) {
        this.tiquete = tiquete;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDireccionEnvio() {
        return this.direccionEnvio;
    }
    
    public void setDireccionEnvio(String direccionEnvio) {
        this.direccionEnvio = direccionEnvio;
    }
    public int getTotal() {
        return this.total;
    }
    
    public void setTotal(int total) {
        this.total = total;
    }
    public String getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Date getVencimiento() {
        return this.vencimiento;
    }
    
    public void setVencimiento(Date vencimiento) {
        this.vencimiento = vencimiento;
    }




}


