package cr.ac.una.prograIV.AirLine.domain;
// Generated 31-may-2017 23:06:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private int pkId;
     private Date fechaSalida;
     private Date horaSalida;
     private Date horaLlegada;
     private Date fechaRegreso;
     private int precio;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Horario() {
    }

	
    public Horario(int pkId, Date fechaSalida, Date horaSalida, Date horaLlegada, int precio) {
        this.pkId = pkId;
        this.fechaSalida = fechaSalida;
        this.horaSalida = horaSalida;
        this.horaLlegada = horaLlegada;
        this.precio = precio;
    }
    public Horario(int pkId, Date fechaSalida, Date horaSalida, Date horaLlegada, Date fechaRegreso, int precio, Set<Vuelo> vuelos) {
       this.pkId = pkId;
       this.fechaSalida = fechaSalida;
       this.horaSalida = horaSalida;
       this.horaLlegada = horaLlegada;
       this.fechaRegreso = fechaRegreso;
       this.precio = precio;
       this.vuelos = vuelos;
    }
   
    public int getPkId() {
        return this.pkId;
    }
    
    public void setPkId(int pkId) {
        this.pkId = pkId;
    }
    public Date getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Date getHoraSalida() {
        return this.horaSalida;
    }
    
    public void setHoraSalida(Date horaSalida) {
        this.horaSalida = horaSalida;
    }
    public Date getHoraLlegada() {
        return this.horaLlegada;
    }
    
    public void setHoraLlegada(Date horaLlegada) {
        this.horaLlegada = horaLlegada;
    }
    public Date getFechaRegreso() {
        return this.fechaRegreso;
    }
    
    public void setFechaRegreso(Date fechaRegreso) {
        this.fechaRegreso = fechaRegreso;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }




}


