package cr.ac.una.prograIV.AirLine.domain;
// Generated 12-may-2017 14:55:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiquete generated by hbm2java
 */
public class Tiquete  implements java.io.Serializable {


     private int pkNumero;
     private Usuario usuario;
     private Vuelo vuelo;
     private boolean idaVuelta;
     private Set<Asiento> asientos = new HashSet<Asiento>(0);

    public Tiquete() {
    }

	
    public Tiquete(int pkNumero, Usuario usuario, Vuelo vuelo, boolean idaVuelta) {
        this.pkNumero = pkNumero;
        this.usuario = usuario;
        this.vuelo = vuelo;
        this.idaVuelta = idaVuelta;
    }
    public Tiquete(int pkNumero, Usuario usuario, Vuelo vuelo, boolean idaVuelta, Set<Asiento> asientos) {
       this.pkNumero = pkNumero;
       this.usuario = usuario;
       this.vuelo = vuelo;
       this.idaVuelta = idaVuelta;
       this.asientos = asientos;
    }
   
    public int getPkNumero() {
        return this.pkNumero;
    }
    
    public void setPkNumero(int pkNumero) {
        this.pkNumero = pkNumero;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }
    public boolean isIdaVuelta() {
        return this.idaVuelta;
    }
    
    public void setIdaVuelta(boolean idaVuelta) {
        this.idaVuelta = idaVuelta;
    }
    public Set<Asiento> getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Set<Asiento> asientos) {
        this.asientos = asientos;
    }




}


