package cr.ac.una.prograIV.AirLine.domain;
// Generated 18-may-2017 21:04:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiquete generated by hbm2java
 */
public class Tiquete  implements java.io.Serializable {


     private int pkNumero;
     private Cliente cliente;
     private Vuelo vuelo;
     private boolean idaVuelta;
     private Set<Asiento> asientos = new HashSet<Asiento>(0);
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Tiquete() {
    }

	
    public Tiquete(int pkNumero, Cliente cliente, Vuelo vuelo, boolean idaVuelta) {
        this.pkNumero = pkNumero;
        this.cliente = cliente;
        this.vuelo = vuelo;
        this.idaVuelta = idaVuelta;
    }
    public Tiquete(int pkNumero, Cliente cliente, Vuelo vuelo, boolean idaVuelta, Set<Asiento> asientos, Set<Compra> compras) {
       this.pkNumero = pkNumero;
       this.cliente = cliente;
       this.vuelo = vuelo;
       this.idaVuelta = idaVuelta;
       this.asientos = asientos;
       this.compras = compras;
    }
   
    public int getPkNumero() {
        return this.pkNumero;
    }
    
    public void setPkNumero(int pkNumero) {
        this.pkNumero = pkNumero;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }
    public boolean isIdaVuelta() {
        return this.idaVuelta;
    }
    
    public void setIdaVuelta(boolean idaVuelta) {
        this.idaVuelta = idaVuelta;
    }
    public Set<Asiento> getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Set<Asiento> asientos) {
        this.asientos = asientos;
    }
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


