package cr.ac.una.prograIV.AirLine.domain;
// Generated 12-may-2017 14:55:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Vuelo generated by hbm2java
 */
public class Vuelo implements java.io.Serializable, Jsonable {

    private int pkNumero;
    private Ciudad ciudadByCiudadDestino;
    private Ciudad ciudadByCiudadOrigen;
    private int costo;
    private Set<Tiquete> tiquetes = new HashSet<Tiquete>(0);

    public String toString() {
        return pkNumero + " " + ciudadByCiudadOrigen + " "
                + ciudadByCiudadDestino + " " + costo;
    }

    public Vuelo() {
    }
     public Vuelo(Vuelo v){
        this.pkNumero = v.pkNumero;
        this.ciudadByCiudadOrigen = new Ciudad(v.getCiudadByCiudadOrigen());
        this.ciudadByCiudadDestino = new Ciudad(v.getCiudadByCiudadDestino());
        this.costo = v.costo;
        this.tiquetes=null;
    }

    public Vuelo(int pkNumero,Ciudad ciudadByCiudadOrigen, Ciudad ciudadByCiudadDestino, int costo) {
        this.pkNumero = pkNumero;
        this.ciudadByCiudadDestino = ciudadByCiudadDestino;
        this.ciudadByCiudadOrigen = ciudadByCiudadOrigen;
        this.costo = costo;
    }

    public Vuelo(int pkNumero, Ciudad ciudadByCiudadDestino, Ciudad ciudadByCiudadOrigen, int costo, Set<Tiquete> tiquetes) {
        this.pkNumero = pkNumero;
        this.ciudadByCiudadDestino = ciudadByCiudadDestino;
        this.ciudadByCiudadOrigen = ciudadByCiudadOrigen;
        this.costo = costo;
        this.tiquetes = tiquetes;
    }

    public int getPkNumero() {
        return this.pkNumero;
    }

    public void setPkNumero(int pkNumero) {
        this.pkNumero = pkNumero;
    }

    public Ciudad getCiudadByCiudadDestino() {
        return this.ciudadByCiudadDestino;
    }

    public void setCiudadByCiudadDestino(Ciudad ciudadByCiudadDestino) {
        this.ciudadByCiudadDestino = ciudadByCiudadDestino;
    }

    public Ciudad getCiudadByCiudadOrigen() {
        return this.ciudadByCiudadOrigen;
    }

    public void setCiudadByCiudadOrigen(Ciudad ciudadByCiudadOrigen) {
        this.ciudadByCiudadOrigen = ciudadByCiudadOrigen;
    }

    public int getCosto() {
        return this.costo;
    }

    public void setCosto(int costo) {
        this.costo = costo;
    }

    public Set<Tiquete> getTiquetes() {
        return this.tiquetes;
    }

    public void setTiquetes(Set<Tiquete> tiquetes) {
        this.tiquetes = tiquetes;
    }

}
